import turtle

turtle.color("red")
turtle.begin_fill()
turtle.goto(70,0)
turtle.setheading(300)
turtle.forward(70)
turtle.setheading(240)
turtle.forward(70)
turtle.setheading(180)
turtle.forward(70)
turtle.setheading(120)
turtle.forward(70)
turtle.goto(0,0)
turtle.end_fill()
turtle.color("black")
turtle.penup()
turtle.goto(35,-70)
turtle.write("stop",align="center",font=("Arial",18,"bold"))
